[Desktop Entry]
Name=cl
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=TraditionalHumanizedCL
MetacityTheme=Human
IconTheme=Human
GtkColorScheme=base_color:#EDE6DD,bg_color:#E6E2DE,fg_color:#101010,selected_bg_color:#F2B566,selected_fg_color:#1A1A1A,tooltip_bg_color:#DBDBA2,tooltip_fg_color:#000000,text_color:#1a1a1a,link_color:#0000ee,visited_link_color:#551a8b
CursorTheme=DMZ-Black
CursorSize=24
